# autogenerated via tools/astgen.nim

import token, literalKind

type
  Expression* = ref object of RootObj

  Binary* = ref object of Expression
    left*: Expression
    operator*: Token
    right*: Expression

  Grouping* = ref object of Expression
    expression*: Expression

  Literal* = ref object of Expression
    case kind*: LiteralKind
      of STRING: sValue*: string
      of NUMBER: fValue*: float
      of BOOLEAN: bValue*: bool
      of NIL: value*: string
      else: discard

  Unary* = ref object of Expression
    operator*: Token
    right*: Expression

