# autogenerated via tools/astgen.nim

import token, literalKind

type
  Expression* = ref object of RootObj
    hasError*: bool

  Binary* = ref object of Expression
    left*: Expression
    operator*: Token
    right*: Expression

  Grouping* = ref object of Expression
    expression*: Expression

  Literal* = ref object of Expression
    case kind*: LiteralKind
      of litString: strVal*: string
      of litNumber: floatVal*: float
      of litBool: boolVal*: bool
      else: discard

  Unary* = ref object of Expression
    operator*: Token
    right*: Expression

