# autogenerated via tools/astgen.nim

import token, literalKind

type
  Expr* = ref object of RootObj
    hasError*: bool

  Binary* = ref object of Expr
    left*: Expr
    operator*: Token
    right*: Expr

  Grouping* = ref object of Expr
    expression*: Expr

  Literal* = ref object of Expr
    case kind*: LiteralKind
      of litString: strVal*: string
      of litNumber: floatVal*: float
      of litBool: boolVal*: bool
      else: discard

  Unary* = ref object of Expr
    operator*: Token
    right*: Expr

