type
  TokenKind* = enum
    # Single-character tokens.
    tkLeftParen,
    tkRightParen,
    tkLeft_brace,
    tkRight_brace,
    tkComma,
    tkDot,
    tkMinus,
    tkPlus,
    tkSemicolon,
    tkSlash,
    tkStar,
    # One or two character tokens.
    tkBang,
    tkBangEqual,
    tkEqual,
    tkEqualEqual,
    tkGreater,
    tkGreaterEqual,
    tkLess,
    tkLessEqual,
    # Literals.
    tkIdentifier,
    tkString,
    tkNumber,
    # Keywords.
    tkAnd,
    tkClass,
    tkElse,
    tkFalse,
    tkFun,
    tkFor,
    tkIf,
    tkNil,
    tkOr,
    tkPrint,
    tkReturn,
    tkSuper,
    tkThis,
    tkTrue,
    tkVar,
    tkWhile,
    tkEof
